In [2]:
import pandas as pd

url = r"C:\Users\User\Documents\Iron Hack\Week5\Project\Project-2-Vanguard-CX-Team\Data\Clean Data\analysis (20).csv"

analysis_df = pd.read_csv(url)

analysis_df

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0

In [16]:
# Sort by client_id	 and date_time to ensure sequence order
analysis_df = analysis_df.sort_values(by=['client_id', 'date_time'])

# Identify backward steps (errors)
analysis_df['next_step'] = analysis_df.groupby('client_id')['process_step'].shift(-1)
analysis_df['backward_move'] = analysis_df['next_step'] < analysis_df['process_step']

# Calculate overall error rates
total_moves = len(analysis_df) - analysis_df['client_id'].nunique()
backward_moves = analysis_df['backward_move'].sum()
error_rate_overall = backward_moves / total_moves if total_moves > 0 else 0

analysis_df['error_rate_overall'] = error_rate_overall


# Display results
print(f"Total Moves: {total_moves}")
print(f"Backward (Error) Moves: {backward_moves}")
print(f"Error Rate: {error_rate_overall:.2%}")

# Optional: View DataFrame to see where backward moves occur
print(analysis_df[['client_id', 'process_step', 'next_step', 'backward_move']])

Total Moves: 266735
Backward (Error) Moves: 63943
Error Rate: 23.97%
        client_id process_step next_step  backward_move
70440         555        start    step_1          False
70439         555       step_1    step_2          False
70438         555       step_2    step_3          False
70437         555       step_3   confirm           True
70436         555      confirm       NaN          False
...           ...          ...       ...            ...
273888    9999729       step_2    step_3          False
273887    9999729       step_3   confirm           True
273886    9999729      confirm       NaN          False
243649    9999832        start    step_1          False
243648    9999832       step_1       NaN          False

[317235 rows x 4 columns]

In [3]:
# Filter for a specific value in a specific column
filtered_value = 'Test'  # The value you're filtering for in the 'category' column
test_df = analysis_df[analysis_df['Variation'] == filtered_value]

# Display the new DataFrame
test_df

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317226,1574008,117364417_77840596075,528720790_71583064618_169151,confirm,2017-05-06 23:51:05,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317227,1574008,117364417_77840596075,528720790_71583064618_169151,step_3,2017-05-06 23:50:40,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317228,1574008,117364417_77840596075,528720790_71583064618_169151,step_2,2017-05-06 23:43:47,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317229,1574008,117364417_77840596075,528720790_71583064618_169151,step_1,2017-05-06 23:43:34,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0

In [12]:
# Sort by client_id	 and date_time to ensure sequence order
test_df = test_df.sort_values(by=['client_id', 'date_time'])

# Identify backward steps (errors)
test_df['next_step'] = test_df.groupby('client_id')['process_step'].shift(-1)
test_df['backward_move'] = test_df['next_step'] < test_df['process_step']

# Calculate error rates
total_moves = len(test_df) - test_df['client_id'].nunique()
backward_moves = test_df['backward_move'].sum()
error_rate_test = backward_moves / total_moves if total_moves > 0 else 0

test_df['error_rate_test'] = error_rate_test


# Display results
print(f"Total Moves: {total_moves}")
print(f"Backward (Error) Moves: {backward_moves}")
print(f"Error Rate: {error_rate_test:.2%}")

# Optional: View DataFrame to see where backward moves occur
print(test_df[['client_id', 'process_step', 'next_step', 'backward_move']])

Total Moves: 149731
Backward (Error) Moves: 37001
Error Rate: 24.71%
        client_id process_step next_step  backward_move
70440         555        start    step_1          False
70439         555       step_1    step_2          False
70438         555       step_2    step_3          False
70437         555       step_3   confirm           True
70436         555      confirm       NaN          False
...           ...          ...       ...            ...
273888    9999729       step_2    step_3          False
273887    9999729       step_3   confirm           True
273886    9999729      confirm       NaN          False
243649    9999832        start    step_1          False
243648    9999832       step_1       NaN          False

[176699 rows x 4 columns]

In [5]:
# Filter for a specific value in a specific column
filtered_value = 'Control'  # The value you're filtering for in the 'category' column
control_df = analysis_df[analysis_df['Variation'] == filtered_value]

# Display the new DataFrame
control_df

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
13,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:03,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
14,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:01,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
15,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:28:52,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
16,4033851,762728880_76361333336,949661017_22392791362_127391,step_3,2017-04-05 12:26:08,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
17,4033851,762728880_76361333336,949661017_22392791362_127391,step_2,2017-04-05 12:24:43,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317224,433098,5505424_50616523266,773565250_67577573147_389841,start,2017-05-13 15:30:47,Control,6.0,73.0,25.0,U,2.0,34419.62,2.0,5.0
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0

In [11]:
# Sort by client_id	 and date_time to ensure sequence order
control_df = control_df.sort_values(by=['client_id', 'date_time'])

# Identify backward steps (errors)
control_df['next_step'] = control_df.groupby('client_id')['process_step'].shift(-1)
control_df['backward_move'] = control_df['next_step'] < control_df['process_step']

# Calculate error rates
total_moves = len(control_df) - control_df['client_id'].nunique()
backward_moves = control_df['backward_move'].sum()
error_rate_control = backward_moves / total_moves if total_moves > 0 else 0

control_df['error_rate_control'] = error_rate_control

# Display results
print(f"Total Moves: {total_moves}")
print(f"Backward (Error) Moves: {backward_moves}")
print(f"Error Rate: {error_rate_control:.2%}")

# Optional: View DataFrame to see where backward moves occur
print(control_df[['client_id', 'process_step', 'next_step', 'backward_move']])

Total Moves: 117004
Backward (Error) Moves: 26942
Error Rate: 23.03%
        client_id process_step next_step  backward_move
129574       1028        start    step_1          False
129573       1028       step_1    step_1          False
129572       1028       step_1    step_2          False
129571       1028       step_2    step_3          False
129570       1028       step_3    step_1           True
...           ...          ...       ...            ...
117037    9998346       step_2    step_3          False
117036    9998346       step_3    step_3          False
117034    9998346       step_3   confirm           True
117035    9998346      confirm       NaN          False
116681    9998921        start       NaN          False

[140536 rows x 4 columns]

In [ ]:
"""# 1. Error Rate Diff (Higher is better)

diffs = {}
diffs['error_rate'] = {
            'absolute_diff': test_df['error_rate_test'] - control_df['error_rate_control'],
            'relative_diff': ((test_df['error_rate_test'] - control_df['error_rate_control']) / control_df['error_rate_control'] * 100)
                            if control_df['error_rate_control'] > 0 else 0,
            'direction': 'improvement' if test_df['error_rate_test'] > control_df['error_rate_control'] else 'regression'
        }


# 3. Error Rate Diff (Lower is better)
diffs['error_rate'] = {
            'absolute_diff': test_df['error_rate_test']['error_rate_overall'] -
                           control_df['error_analysis']['error_rate_overall'],
            'relative_diff': ((test_df['error_rate_test']['error_rate_overall'] -
                             control_df['error_rate_control']['error_rate_overall']) /
                            control_df['error_rate_control']['error_rate_overall'] * 100)
                           if control_df['error_rate_control']['error_rate_overall'] > 0 else 0,
            'direction': 'improvement' if test_df['error_rate_test']['error_rate_overall'] <
                        control_df['error_rate_control']['error_rate_overall'] else 'regression'
        }"""

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set styling
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("Set2")

analysis_df['date_time'] = pd.to_datetime(analysis_df['date_time'])

print("="*80)
print("VANGUARD A/B TEST - KPI ANALYSIS")
print("="*80)
print(f"\nDataset Overview:")
print(f"  Total Records: {len(analysis_df):,}")
print(f"  Unique Clients: {analysis_df['client_id'].nunique():,}")
print(f"  Date Range: {analysis_df['date_time'].min().date()} to {analysis_df['date_time'].max().date()}")
print(f"\nVariation Distribution:")
print(analysis_df['Variation'].value_counts())


# ============================================================================
# KPI 1: COMPLETION RATE
# ============================================================================

print("\n" + "="*80)
print("KPI 1: COMPLETION RATE")
print("="*80)
print("Definition: Proportion of users who reach the final 'confirm' step\n")

# Count total unique clients per variation
total_clients = analysis_df.groupby('Variation')['client_id'].nunique()

# Count clients who reached 'confirm' step
completed_clients = analysis_df[analysis_df['process_step'] == 'confirm'].groupby('Variation')['client_id'].nunique()

# Calculate completion rate
completion_rate = (completed_clients / total_clients * 100).round(2)

# Display results
print("Total Clients:")
print(total_clients)
print("\nClients Who Completed:")
print(completed_clients)
print("\n📊 COMPLETION RATE:")
for var in completion_rate.index:
    print(f"  {var:12s}: {completion_rate[var]:6.2f}%")

# Calculate improvement
if 'Test' in completion_rate.index and 'Control' in completion_rate.index:
    abs_diff = completion_rate['Test'] - completion_rate['Control']
    rel_diff = ((completion_rate['Test'] / completion_rate['Control']) - 1) * 100
    
    print(f"\n🎯 IMPROVEMENT:")
    print(f"  Absolute: {abs_diff:+.2f} percentage points")
    print(f"  Relative: {rel_diff:+.2f}%")
    
    if abs_diff > 0:
        print(f"  ✅ Test group shows HIGHER completion rate")
    elif abs_diff < 0:
        print(f"  ❌ Test group shows LOWER completion rate")
    else:
        print(f"  ➖ No difference in completion rate")


# ============================================================================
# KPI 2: TIME SPENT ON EACH STEP
# ============================================================================

print("\n" + "="*80)
print("KPI 2: TIME SPENT ON EACH STEP")
print("="*80)
print("Definition: Average duration users spend on each step\n")

# Sort data by client, visit, and timestamp
df_sorted = analysis_df.sort_values(['client_id', 'visit_id', 'date_time']).copy()

# Calculate time difference between consecutive steps within same visit
df_sorted['time_diff'] = df_sorted.groupby(['client_id', 'visit_id'])['date_time'].diff()

# Convert to seconds then minutes
df_sorted['time_diff_seconds'] = df_sorted['time_diff'].dt.total_seconds()
df_sorted['time_diff_minutes'] = df_sorted['time_diff_seconds'] / 60

# Filter outliers: Remove sessions > 60 minutes (likely abandoned/interrupted)
df_sorted.loc[df_sorted['time_diff_minutes'] > 60, 'time_diff_minutes'] = np.nan

# Calculate average time per step by variation
time_per_step = df_sorted.groupby(['Variation', 'process_step'])['time_diff_minutes'].agg([
    ('mean', 'mean'),
    ('median', 'median'),
    ('count', 'count')
]).round(2)

print("📊 AVERAGE TIME PER STEP (minutes):")
print(time_per_step)

# Calculate total journey time
total_journey = df_sorted.groupby(['Variation', 'client_id', 'visit_id'])['time_diff_minutes'].sum()
avg_total_time = total_journey.groupby('Variation').agg(['mean', 'median', 'std']).round(2)

print("\n📊 AVERAGE TOTAL JOURNEY TIME (minutes):")
print(avg_total_time)




# Compare Control vs Test
if 'Test' in avg_total_time.index and 'Control' in avg_total_time.index:
    time_diff = avg_total_time.loc['Test', 'mean'] - avg_total_time.loc['Control', 'mean']
    time_pct = (time_diff / avg_total_time.loc['Control', 'mean']) * 100
    
    print(f"\n🎯 JOURNEY TIME COMPARISON:")
    print(f"  Difference: {time_diff:+.2f} minutes ({time_pct:+.1f}%)")
    if time_diff < 0:
        print(f"  ✅ Test group is FASTER")
    elif time_diff > 0:
        print(f"  ❌ Test group is SLOWER")
    else:
        print(f"  ➖ No time difference")


# ============================================================================
# KPI 3: ERROR RATE
# ============================================================================

================================================================================
VANGUARD A/B TEST - KPI ANALYSIS
================================================================================

Dataset Overview:
  Total Records: 317,235
  Unique Clients: 50,500
  Date Range: 2017-03-15 to 2017-06-20

Variation Distribution:
Variation
Test       176699
Control    140536
Name: count, dtype: int64

================================================================================
KPI 1: COMPLETION RATE
================================================================================
Definition: Proportion of users who reach the final 'confirm' step

Total Clients:
Variation
Control    23532
Test       26968
Name: client_id, dtype: int64

Clients Who Completed:
Variation
Control    15434
Test       18687
Name: client_id, dtype: int64

📊 COMPLETION RATE:
  Control     :  65.59%
  Test        :  69.29%

🎯 IMPROVEMENT:
  Absolute: +3.70 percentage points
  Relative: +5.64%
  ✅ Test group shows HIGHER completion rate

================================================================================
KPI 2: TIME SPENT ON EACH STEP
================================================================================
Definition: Average duration users spend on each step

📊 AVERAGE TIME PER STEP (minutes):
                        mean  median  count
Variation process_step
Control   confirm       2.15    1.22  16570
          start         2.73    0.85  14455
          step_1        0.72    0.30  29258
          step_2        0.65    0.33  25659
          step_3        1.57    1.10  22329
Test      confirm       2.13    0.95  22204
          start         2.43    0.95  22694
          step_1        0.63    0.18  38346
          step_2        0.80    0.42  30728
          step_3        1.62    1.10  25493

📊 AVERAGE TOTAL JOURNEY TIME (minutes):
           mean  median   std
Variation
Control    4.58    2.65  7.04
Test       5.18    2.78  8.81

🎯 JOURNEY TIME COMPARISON:
  Difference: +0.60 minutes (+13.1%)
  ❌ Test group is SLOWER