In [1]:
import pandas as pd
import scipy.stats as st
import numpy as np

df = pd.read_csv(r"C:\Users\User\Documents\Iron Hack\Week5\Project\Project-2-Vanguard-CX-Team\Data\Clean Data\analysis.csv")

In [2]:
df

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0

In [5]:
#Define the hypotheses

#H0: average client tenure is the same for both groups/ mean of clnt_tenure_yr_control = mean of clnt_tenure_yr_test
#H1: average client tenure is different for the two groups/mean of clnt_tenure_yr_control != mean of clnt_tenure_yr_test

#choose the significance level: 0.05

#obtain average tenures and variance for both groups

stats = df.groupby('Variation')['clnt_tenure_yr'].agg(['mean', 'var']).reset_index()

stats

  Variation       mean        var
0   Control  12.167438  48.730607
1      Test  12.182025  48.170847

In [6]:
from scipy.stats import ttest_ind

# Extract the tenure data for each group
tenure_test = df[df['Variation'] == 'Test']['clnt_tenure_yr']
tenure_control = df[df['Variation'] == 'Control']['clnt_tenure_yr']

# Perform a two-sample t-test
t_stat, p_value = ttest_ind(tenure_test, tenure_control, equal_var=False)  # Welch's t-test

# Print the results
print(f"T-statistic: {t_stat:.4f}")
print(f"P-value: {p_value:.4f}")

# Decision
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a statistically significant difference in average client tenure.")
else:
    print("Fail to reject the null hypothesis. There is no statistically significant difference in average client tenure.")

T-statistic: nan
P-value: nan
Fail to reject the null hypothesis. There is no statistically significant difference in average client tenure.

In [7]:
# Check for missing values
if df['clnt_tenure_yr'].isnull().any():
    print("There are missing values in the Tenure column.")

There are missing values in the Tenure column.

In [9]:
# Remove rows with missing 'Tenure' values
df_clean = df.dropna(subset=['clnt_tenure_yr'])

df_clean

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0

In [12]:
# Check for missing values
if df_clean['clnt_tenure_yr'].isnull().any():
    print("There are missing values in the Tenure column.")

In [13]:
from scipy.stats import ttest_ind

# Extract the tenure data for each group
tenure_test = df_clean[df_clean['Variation'] == 'Test']['clnt_tenure_yr']
tenure_control = df_clean[df_clean['Variation'] == 'Control']['clnt_tenure_yr']

# Perform a two-sample t-test
t_stat, p_value = ttest_ind(tenure_test, tenure_control, equal_var=False)  # Welch's t-test

# Print the results
print(f"T-statistic: {t_stat:.4f}")
print(f"P-value: {p_value:.4f}")

# Decision
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a statistically significant difference in average client tenure.")
else:
    print("Fail to reject the null hypothesis. There is no statistically significant difference in average client tenure.")

T-statistic: 0.5860
P-value: 0.5579
Fail to reject the null hypothesis. There is no statistically significant difference in average client tenure.